/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/admin/users': RouteRecordInfo<
      '/admin/users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth': RouteRecordInfo<
      '/auth',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | '/auth/'
      | '/auth/forgot-password'
      | '/auth/otp'
      | '/auth/sign-in'
      | '/auth/sign-up'
    >,
    '/auth/': RouteRecordInfo<
      '/auth/',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/forgot-password': RouteRecordInfo<
      '/auth/forgot-password',
      '/auth/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/otp': RouteRecordInfo<
      '/auth/otp',
      '/auth/otp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-in': RouteRecordInfo<
      '/auth/sign-in',
      '/auth/sign-in',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-up': RouteRecordInfo<
      '/auth/sign-up',
      '/auth/sign-up',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bills/create': RouteRecordInfo<
      '/bills/create',
      '/bills/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bills/delete': RouteRecordInfo<
      '/bills/delete',
      '/bills/delete',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bills/list': RouteRecordInfo<
      '/bills/list',
      '/bills/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/data/brands': RouteRecordInfo<
      '/data/brands',
      '/data/brands',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/data/companies': RouteRecordInfo<
      '/data/companies',
      '/data/companies',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/data/destinations': RouteRecordInfo<
      '/data/destinations',
      '/data/destinations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/data/sale-deps': RouteRecordInfo<
      '/data/sale-deps',
      '/data/sale-deps',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/data/vehicles': RouteRecordInfo<
      '/data/vehicles',
      '/data/vehicles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/data/warehouses': RouteRecordInfo<
      '/data/warehouses',
      '/data/warehouses',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/data-process/plate': RouteRecordInfo<
      '/data-process/plate',
      '/data-process/plate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/data-process/round-steel': RouteRecordInfo<
      '/data-process/round-steel',
      '/data-process/round-steel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors': RouteRecordInfo<
      '/errors',
      '/errors',
      Record<never, never>,
      Record<never, never>,
      | '/errors/'
      | '/errors/401'
      | '/errors/403'
      | '/errors/404'
      | '/errors/500'
      | '/errors/503'
    >,
    '/errors/': RouteRecordInfo<
      '/errors/',
      '/errors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/401': RouteRecordInfo<
      '/errors/401',
      '/errors/401',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/403': RouteRecordInfo<
      '/errors/403',
      '/errors/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/404': RouteRecordInfo<
      '/errors/404',
      '/errors/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/500': RouteRecordInfo<
      '/errors/500',
      '/errors/500',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/503': RouteRecordInfo<
      '/errors/503',
      '/errors/503',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/help-center': RouteRecordInfo<
      '/help-center',
      '/help-center',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/invoices/create-ship': RouteRecordInfo<
      '/invoices/create-ship',
      '/invoices/create-ship',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/invoices/create-truck': RouteRecordInfo<
      '/invoices/create-truck',
      '/invoices/create-truck',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/invoices/delete': RouteRecordInfo<
      '/invoices/delete',
      '/invoices/delete',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plans/': RouteRecordInfo<
      '/plans/',
      '/plans',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plans/create': RouteRecordInfo<
      '/plans/create',
      '/plans/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/business': RouteRecordInfo<
      '/platform/business',
      '/platform/business',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/statistics': RouteRecordInfo<
      '/platform/statistics',
      '/platform/statistics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/platform/tenants': RouteRecordInfo<
      '/platform/tenants',
      '/platform/tenants',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reports/customer-revenue': RouteRecordInfo<
      '/reports/customer-revenue',
      '/reports/customer-revenue',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reports/drayage-forklift/': RouteRecordInfo<
      '/reports/drayage-forklift/',
      '/reports/drayage-forklift',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reports/integrated': RouteRecordInfo<
      '/reports/integrated',
      '/reports/integrated',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reports/invoice': RouteRecordInfo<
      '/reports/invoice',
      '/reports/invoice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reports/shipping-charge': RouteRecordInfo<
      '/reports/shipping-charge',
      '/reports/shipping-charge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reports/vessel-fixed-cost/': RouteRecordInfo<
      '/reports/vessel-fixed-cost/',
      '/reports/vessel-fixed-cost',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reports/vessel-revenue': RouteRecordInfo<
      '/reports/vessel-revenue',
      '/reports/vessel-revenue',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/account': RouteRecordInfo<
      '/settings/account',
      '/settings/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/appearance': RouteRecordInfo<
      '/settings/appearance',
      '/settings/appearance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/display': RouteRecordInfo<
      '/settings/display',
      '/settings/display',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settle/bill': RouteRecordInfo<
      '/settle/bill',
      '/settle/bill',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settle/money': RouteRecordInfo<
      '/settle/money',
      '/settle/money',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settle/ticket': RouteRecordInfo<
      '/settle/ticket',
      '/settle/ticket',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settle/vessel': RouteRecordInfo<
      '/settle/vessel',
      '/settle/vessel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sva-components/': RouteRecordInfo<
      '/sva-components/',
      '/sva-components',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/admin/users.vue': {
      routes:
        | '/admin/users'
      views:
        | never
    }
    'src/pages/auth.vue': {
      routes:
        | '/auth'
        | '/auth/'
        | '/auth/forgot-password'
        | '/auth/otp'
        | '/auth/sign-in'
        | '/auth/sign-up'
      views:
        | 'default'
    }
    'src/pages/auth/index.vue': {
      routes:
        | '/auth/'
      views:
        | never
    }
    'src/pages/auth/forgot-password.vue': {
      routes:
        | '/auth/forgot-password'
      views:
        | never
    }
    'src/pages/auth/otp.vue': {
      routes:
        | '/auth/otp'
      views:
        | never
    }
    'src/pages/auth/sign-in.vue': {
      routes:
        | '/auth/sign-in'
      views:
        | never
    }
    'src/pages/auth/sign-up.vue': {
      routes:
        | '/auth/sign-up'
      views:
        | never
    }
    'src/pages/bills/create.vue': {
      routes:
        | '/bills/create'
      views:
        | never
    }
    'src/pages/bills/delete.vue': {
      routes:
        | '/bills/delete'
      views:
        | never
    }
    'src/pages/bills/list.vue': {
      routes:
        | '/bills/list'
      views:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
    }
    'src/pages/data/brands.vue': {
      routes:
        | '/data/brands'
      views:
        | never
    }
    'src/pages/data/companies.vue': {
      routes:
        | '/data/companies'
      views:
        | never
    }
    'src/pages/data/destinations.vue': {
      routes:
        | '/data/destinations'
      views:
        | never
    }
    'src/pages/data/sale-deps.vue': {
      routes:
        | '/data/sale-deps'
      views:
        | never
    }
    'src/pages/data/vehicles.vue': {
      routes:
        | '/data/vehicles'
      views:
        | never
    }
    'src/pages/data/warehouses.vue': {
      routes:
        | '/data/warehouses'
      views:
        | never
    }
    'src/pages/data-process/plate.vue': {
      routes:
        | '/data-process/plate'
      views:
        | never
    }
    'src/pages/data-process/round-steel.vue': {
      routes:
        | '/data-process/round-steel'
      views:
        | never
    }
    'src/pages/errors.vue': {
      routes:
        | '/errors'
        | '/errors/'
        | '/errors/401'
        | '/errors/403'
        | '/errors/404'
        | '/errors/500'
        | '/errors/503'
      views:
        | 'default'
    }
    'src/pages/errors/index.vue': {
      routes:
        | '/errors/'
      views:
        | never
    }
    'src/pages/errors/401.vue': {
      routes:
        | '/errors/401'
      views:
        | never
    }
    'src/pages/errors/403.vue': {
      routes:
        | '/errors/403'
      views:
        | never
    }
    'src/pages/errors/404.vue': {
      routes:
        | '/errors/404'
      views:
        | never
    }
    'src/pages/errors/500.vue': {
      routes:
        | '/errors/500'
      views:
        | never
    }
    'src/pages/errors/503.vue': {
      routes:
        | '/errors/503'
      views:
        | never
    }
    'src/pages/help-center.vue': {
      routes:
        | '/help-center'
      views:
        | never
    }
    'src/pages/invoices/create-ship.vue': {
      routes:
        | '/invoices/create-ship'
      views:
        | never
    }
    'src/pages/invoices/create-truck.vue': {
      routes:
        | '/invoices/create-truck'
      views:
        | never
    }
    'src/pages/invoices/delete.vue': {
      routes:
        | '/invoices/delete'
      views:
        | never
    }
    'src/pages/plans/index.vue': {
      routes:
        | '/plans/'
      views:
        | never
    }
    'src/pages/plans/create.vue': {
      routes:
        | '/plans/create'
      views:
        | never
    }
    'src/pages/platform/business.vue': {
      routes:
        | '/platform/business'
      views:
        | never
    }
    'src/pages/platform/statistics.vue': {
      routes:
        | '/platform/statistics'
      views:
        | never
    }
    'src/pages/platform/tenants.vue': {
      routes:
        | '/platform/tenants'
      views:
        | never
    }
    'src/pages/reports/customer-revenue.vue': {
      routes:
        | '/reports/customer-revenue'
      views:
        | never
    }
    'src/pages/reports/drayage-forklift/index.vue': {
      routes:
        | '/reports/drayage-forklift/'
      views:
        | never
    }
    'src/pages/reports/integrated.vue': {
      routes:
        | '/reports/integrated'
      views:
        | never
    }
    'src/pages/reports/invoice.vue': {
      routes:
        | '/reports/invoice'
      views:
        | never
    }
    'src/pages/reports/shipping-charge.vue': {
      routes:
        | '/reports/shipping-charge'
      views:
        | never
    }
    'src/pages/reports/vessel-fixed-cost/index.vue': {
      routes:
        | '/reports/vessel-fixed-cost/'
      views:
        | never
    }
    'src/pages/reports/vessel-revenue.vue': {
      routes:
        | '/reports/vessel-revenue'
      views:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
    }
    'src/pages/settings/account.vue': {
      routes:
        | '/settings/account'
      views:
        | never
    }
    'src/pages/settings/appearance.vue': {
      routes:
        | '/settings/appearance'
      views:
        | never
    }
    'src/pages/settings/display.vue': {
      routes:
        | '/settings/display'
      views:
        | never
    }
    'src/pages/settle/bill.vue': {
      routes:
        | '/settle/bill'
      views:
        | never
    }
    'src/pages/settle/money.vue': {
      routes:
        | '/settle/money'
      views:
        | never
    }
    'src/pages/settle/ticket.vue': {
      routes:
        | '/settle/ticket'
      views:
        | never
    }
    'src/pages/settle/vessel.vue': {
      routes:
        | '/settle/vessel'
      views:
        | never
    }
    'src/pages/sva-components/index.vue': {
      routes:
        | '/sva-components/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
